#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE SCHEMA IF NOT EXISTS collector;
  CREATE SCHEMA IF NOT EXISTS normalizer;
  CREATE SCHEMA IF NOT EXISTS market;
  CREATE SCHEMA IF NOT EXISTS signals;
  CREATE SCHEMA IF NOT EXISTS risk;
  CREATE SCHEMA IF NOT EXISTS explain;
  CREATE SCHEMA IF NOT EXISTS api;
  CREATE SCHEMA IF NOT EXISTS simulation;
EOSQL
